# Generated by Django 2.2.4 on 2019-08-24 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20180624_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating',
                 models.IntegerField(choices=[(0, 'отсутствует'), (1, 'неуд'), (2, 'удовл'), (3, 'хор'), (4, 'отл')],
                                     db_index=True, default=0, verbose_name='рейтинг продукта от пользователя')),
                ('rating_product',
                 models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Product')),
                ('rating_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
